[project]
name = "backend2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cohere>=5.20.1",
    "fastapi>=0.127.1",
    "openai-agents>=0.2.10",
    "python-dotenv>=1.1.1",
    "qdrant-client>=1.16.2",
]
